name: 'MinGW'

env:
  DEPLOY_FILE_NOEXT: nCine-external-OS-COMPILER-VERSION
  DEPLOY_MESSAGE:
    "Push artifact from GitHub Actions build ${{ github.run_number }} with id ${{ github.run_id }}

     - nCine-libraries artifact from branch 'BRANCH_NAME' with commit id ${{ github.sha }}"
  DEPLOY_BRANCH: libraries-OS-COMPILER

on: [push, workflow_dispatch]

jobs:
  MinGW:
    strategy:
      fail-fast: false
      matrix:
        include:
        - BuildType: Debug
          CC: gcc
          CXX: g++

        - BuildType: Release
          CC: gcc
          CXX: g++

        - BuildType: Debug
          CC: clang
          CXX: clang++

        - BuildType: Release
          CC: clang
          CXX: clang++

    runs-on: 'windows-2019'

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v3

    - name: 'Update MSYS2 on Windows'
      run: |
        $env:MSYSTEM = "MINGW64"

        C:\msys64\usr\bin\bash.exe -lc 'pacman --noconfirm -Syyuu'
        C:\msys64\usr\bin\bash.exe -lc 'pacman --noconfirm -Syyuu'

    - name: 'Install Build Dependencies'
      run: |
        $env:MSYSTEM = "MINGW64"

        C:\msys64\usr\bin\bash.exe -lc 'pacman --needed --noconfirm -S cmake'

        if ("${{ matrix.CC }}" -eq "gcc") { C:\msys64\usr\bin\bash.exe -lc 'pacman --needed --noconfirm -S mingw-w64-x86_64-gcc' }
        else { C:\msys64\usr\bin\bash.exe -lc 'pacman --needed --noconfirm -S mingw-w64-x86_64-clang' }

        C:\msys64\usr\bin\bash.exe -lc 'pacman --noconfirm -Scc'

    - name: 'CMake Configuration'
      env:
        CHERE_INVOKING: on
      run: |
        $env:CC = "${{ matrix.CC }}"
        $env:CXX= "${{ matrix.CXX }}"

        $env:MSYSTEM = "MINGW64"
        C:\msys64\usr\bin\bash.exe -lc 'cmake -G \"MSYS Makefiles\" -B ../nCine-libraries-build -D CMAKE_BUILD_TYPE=${{ matrix.BuildType }}'

    - name: 'Make'
      env:
        CHERE_INVOKING: on
      run: |
        $env:MSYSTEM = "MINGW64"
        C:\msys64\usr\bin\bash.exe -lc 'make -j2 -C ../nCine-libraries-build'

    - name: 'Push Artifacts'
      if: matrix.BuildType == 'Release'
      env:
        PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        $env:GIT_REDIRECT_STDERR = '2>&1'

        $env:branch_name = git describe --tags --exact-match; if (-not $?) { $env:branch_name = git symbolic-ref -q --short HEAD }; if (-not $?) { $env:branch_name = git rev-parse --short HEAD }
        $env:DEPLOY_MESSAGE = $env:DEPLOY_MESSAGE -replace "BRANCH_NAME",$env:branch_name

        git fetch --unshallow; if (-not $?) { return }
        git describe --tags --long 2>$null; if ($?) { $env:git_version = git describe --tags --long 2>$null | %{$_ -replace "([^-]*-g)","r`$1" -replace "-","."} } else { $env:git_version = -join("r", $(git rev-list --count HEAD), ".", $(git rev-parse --short HEAD)) }
        cd ..

        $env:CC = "${{ matrix.CC }}"
        $env:DEPLOY_FILE = -join($env:DEPLOY_FILE_NOEXT, ".7z")
        $env:DEPLOY_FILE = $env:DEPLOY_FILE -replace "OS","mingw64" -replace "COMPILER",$env:CC -replace "VERSION",$env:git_version
        $env:DEPLOY_BRANCH = $env:DEPLOY_BRANCH -replace "OS","mingw64" -replace "COMPILER",$env:CC
        7z a $env:DEPLOY_FILE nCine-external

        git clone https://$env:PUBLIC_REPO_TOKEN@github.com/nCine/nCine-libraries-artifacts.git 2>&1>$null
        cd nCine-libraries-artifacts
        git checkout $env:DEPLOY_BRANCH; if (-not $?) { git checkout --orphan $env:DEPLOY_BRANCH }
        git reset
        git clean -f
        git rm *
        Move-Item -Path ..\$env:DEPLOY_FILE -Destination .
        git add $env:DEPLOY_FILE
        git commit --amend -m "$env:DEPLOY_MESSAGE"; if (-not $?) { git commit -m "$env:DEPLOY_MESSAGE" }
        git push --force; if (-not $?) { git push --set-upstream origin $env:DEPLOY_BRANCH }
